### PR TITLE
Added a TypeScript implementation for JS Assert.

### PR DESCRIPTION
**Pull request by Corniel**
TypeScript is taking of, and I thought it would be nice to allow writing the JS part of the unit tests in type script.

### CODE REVIEW

**Comment by cbaxter** [comment]
@Corniel Nice! I will check it out later this week,

**Comment by Corniel** [comment]
What's the status?

**Comment by cbaxter** [comment]
@Corniel To be perfectly honest, it has completely slipped my mind... I no longer use this library for my projects and unfortunately have let things fall behind. The change itself looks straight forward and I would only have to run a quick test to verify that the PR is valid; I will try to get to it today, but I am leaving for a long-overdue vacation tomorrow so I cannot make any promises.

**Comment by Corniel** [comment]
Don't hurry. If you think there are better ways now, (and that might be the case) that is also an answer. I felt the need for this library two years ago, but that project was abandoned. Now there is a new project I need something similar for, so I was just checking the status again. Join your trip.

**Comment by cbaxter** [comment]
@Corniel After further thought, I am not going to pursue this PR further; I would look in to options for running JavaScript/TypeScript unit tests in Node or similar... this library was useful back in the day, but at this stage I think it has outlived it's usefulness with modern tooling.

**Comment by Corniel** [comment]
Fair enough.

**Pull request closed without merging**
