### PR TITLE
Make TestExecutor public to support test setup and cleanup in javascript.

### PR DESCRIPTION
**Pull request by dzwarg**
- Changed the TestExecutor class to public, and the RunTest method to public.
- Removed the 'return' statement from TestCase.ToScriptFragment, which prevents any cleanup script from running.

These changes allow setup/cleanup scripts to be specified in an executor, and TestScript.RunTest(TestExecutor) can run setup/cleanup scripts, in addition to tests.

### CODE REVIEW

**Comment by cbaxter** [comment]
@dzwarg Agreed. I will expose a way to provide custom set-up/tear down via the current API and leave the TestExecutor internal. I was also thinking the same thing with regard to holding on to the return value until after tear-down. I will make the changes soon (may not be able to get to it today, but should be able to work on it tomorrow or Wednesday).

**Comment by cbaxter** [comment]
@dzwarg Didn't get a chance to make the change tonight, but I will get it done tomorrow evening. Should actually be a really small change... sorry for the delay.

**Comment by dzwarg** [comment]
@cbaxter No problem, thanks in advance for taking the time to do it.

**Comment by cbaxter** [comment]
@dzwarg Taking a closer look, I am curious how you were using TestCase? Given that you have a test file with a series of unit tests, is your setup/teardown code for those unit tests located in the same file, or sourced from elsewhere?

If the setup/teardown was in the source file itself, then it may make sense to extend `TestCase` to explicitly flag the setup/teardown methods and wrap the function invocation inside the `TestCase` class. If the setup/teardown was sourced from elsewhere then the additional of the following new `RunTest` overload would be sufficient.

`public String RunTest(String testScript, String setup, String teardown)`

_Assuming the `return` issue was also handled_

If you could provide a little more insight, it would be appreciated to ensure that the API is extended in the best possible way. Thank you.

**Comment by dzwarg** [comment]
@cbaxter My teardown script is outside of the JavaScript test file.

My original problem that I was trying to solve was that I have some custom setup code that fakes a browser, in order to use jQuery.  Part of faking the browser is that you need to close the fake browser at some point, so I use a script line to do so.  A full example:

``` csharp
[Theory]
public void Test(TestCase testCase)
{
    var script = new TestScript { IncludeDefaultBreakpoint = true };

    script.AppendBlock(new JsAssertLibrary());
    script.AppendFile(@"..\..\dom.js");
    script.AppendFile(@"..\..\Scripts\jquery.js");
    script.AppendBlock(@"var $ = window.$;");

    script.AppendFile(@"..\..\Scripts\module.js");

    script.AppendFile(testCase.TestFile);

    TestExecutor exec = new TestExecutor(String.Empty, testCase.ToScriptFragment(), "ie.Quit();");

    script.RunTest(exec);
}
```

This uses a short script that creates a headless browser (IE) in dom.js, and aliases the window  & properties  (of the headless browser) to global variables -- jQuery needs access to `window`, `document`, `setTimeout`, etc.

At the end, I just need a short snippet to quit the browser.  It can't be a script file, because it needs to get inserted into that method that TextExecutor creates.  This is the work around that I was using because it seemed to fit the JSTest.NET model in a neat way.

I think that having a new `RunTest` overload that takes a setup & teardown parameter would also work just as well.

**Comment by cbaxter** [comment]
@dzwarg Thank you for the additional information. Based on the provided use case, all is required is the additional `RunTest` overload along with some form of handling the `return {0}();` when a TestCase is converted to a script fragment. I will push the changes tonight or tomorrow.

**Comment by cbaxter** [comment]
@dzwarg I have pushed the required code change in 5613e9f61e8c6dfe079f22ff3690d9750d5d6799.

Please verify the change and if everything works as you would expect I will package and post a new NuGet package.

**Comment by dzwarg** [comment]
@cbaxter Works great! Thank you!

**Comment by cbaxter** [comment]
@dzwarg Excellent, I will push new NuGet packages tonight.

**Pull request closed without merging**
